### ISSUE TITLE
[Dev] Extensions

### ISSUE THREAD

**Issue by ocots** [control-toolbox/OptimalControlProblems.jl#12]
We could make two extensions containing respectively `JuMPModels` and `OptimalControlModels`. 

The module `JuMPModels` would be triggered by `using JuMP` and `OptimalControlModels` by `OptimalControl`. 

This would reduce what is loaded for instance if a user only wants to load `OptimalControl` models.

```julia
using OptimalControl
using OptimalControlProblems

nlp = OptimalControlModels.cart_pendulum()
```

>[!NOTE]
> [CTBasePlots.jl](https://github.com/control-toolbox/CTBase.jl/blob/main/ext/CTBasePlots.jl) is an extension of `CTBase.jl`. To trigger it, see the [Project.toml](https://github.com/control-toolbox/CTBase.jl/blob/a9744ff7cfaed4126c2bdbddce55b8adbf344010/Project.toml#L24-L25).

**Comment by ocots** [comment]
Another possibility is to write:

```julia
using OptimalControl
using OptimalControlProblems

nlp = cart_pendulum(; model=:optimalcontrol)
```

or 

```julia
using JuMP
using OptimalControlProblems

nlp = cart_pendulum(; model=:jump)
```

with an error of the form:

```julia
julia> using JuMP
julia> using OptimalControlProblems

julia> nlp = cart_pendulum(; model=:optimalcontrol)
ERROR: ExtensionError. Please make: julia> using OptimalControl
```

**Comment by frapac** [comment]
I would be in favor of not complexifying  too much OptimalControlProblems.jl, and I don't think we should use package extensions at the moment. 

I think it's reasonable to assume both JuMP and OptimalControl as direct dependencies there, as they are both complementary to formulate OCP. 

Package extensions would make sense if we want to add more backends to the benchmark library.

**Comment by frapac** [comment]
Regarding your second point, I think a more Julian way would be to use multiple dispatch. Something like: 

```julia
# template 
function cart_pendulum end 

abstract type AbstractOCPBackend end 

struct JuMPBackend <: AbstractOCPBackend end

function cart_pendulum(::JuMPBackend) 
    # some code
end

struct OptimalControlBackend <: AbstractOCPBackend end

function cart_pendulum(::OptimalControlBackend) 
    # some code
end

```
The problem can be instantiated e.g. as 
```julia
nlp = cart_pendulum(JuMPBackend())
```
That way an error is automatically thrown if the backend is not defined.

**Comment by ocots** [comment]
> I would be in favor of not complexifying too much OptimalControlProblems.jl, and I don't think we should use package extensions at the moment.
> 
> I think it's reasonable to assume both JuMP and OptimalControl as direct dependencies there, as they are both complementary to formulate OCP.
> 
> Package extensions would make sense if we want to add more backends to the benchmark library.

I agree with the fact that we should not complexify too much for the user and for someone who want to add models. I do not think that this is so complex to make an extension and for the user, it changes just the fact that he has to make an additional `using` and if you want to add problems, it does not change anything.

I would be in favor to make extensions because it is very nice to reduce as much as possible time for installation, precompilation, etc.

One use case is the following: we will make some tests inside `CTDirect.jl` using some problems from `OptimalControlProblems.jl`. In this use case there is no need of `Jump` models. Besides, to define an `OptimalControlModel`, we do not need `OptimalControl.jl` but simply `CTBase.jl`. So to trigger `OptimalControlModels`, we should add in the weak dependencies not `OptimalControl` but `CTBase`. Like that both `CTBase.jl` and `OptimalControl.jl` will trigger it since `OptimalControl` load `CTBase`.

@PierreMartinon Any thoughts?

**Comment by ocots** [comment]
For the second point, I agree with but I have hidden multiple dispatch. I like the user does not care about types. The function with the `model` keyword would call a function with multiple dispatch.

**Comment by frapac** [comment]
> One use case is the following: we will make some tests inside CTDirect.jl using some problems from OptimalControlProblems.jl. 

I see your point. In that case let's follow your idea. 

> I like the idea that the user should not care about types. The function with the model keyword would call a function with multiple dispatch.

I see. But is that compatible with package extensions? As far as I understand, you will have to define the structs `JuMPBackend` and `OptimalControlBackend` in the main repo to define your switch statement as
```julia
function cart_pendulum(; model=:optimalcontrol)
     if model == :optimalcontrol
         cart_pendulum(OptimalControlBackend())
     elseif model == :jump
         cart_pendulum(JuMPBackend())
     else
          error("...")
     end
end
```
Is that the idea? If so I think this will lead to a lot of boilerplate code, and hinder the package's extensibility if we want to plug additional backends.

**Comment by ocots** [comment]
For the second point you are completely right. In `CTDirect.jl`, we have in the main module:

```julia
abstract type SolverTag end
struct IpoptTag <: SolverTag end
struct MadNLPTag <: SolverTag end

function solve_docp(solver_tag, args...; kwargs...)
    if typeof(solver_tag) == IpoptTag
        throw(ExtensionError(:NLPModelsIpopt))
    elseif typeof(solver_tag) == MadNLPTag
        throw(ExtensionError(:MadNLP))
    else
        error("Unknown solver type", typeof(solver_tag))
    end
end
```

and in the extension `CTSolveExtMadNLP.jl`:

```julia
function CTDirect.solve_docp(
    tag::CTDirect.MadNLPTag,
    docp::CTDirect.DOCP,
    nlp;
    display::Bool = CTBase.__display(),
    max_iter::Integer = CTDirect.__max_iterations(),
    tol::Real = CTDirect.__tolerance(),
    linear_solver::String = CTDirect.__madnlp_linear_solver(),
    kwargs...,
)
...
end
```

**Comment by ocots** [comment]
For the second point you will have the following.

In the main module:

```julia
abstract type AbstractModelBackend end
struct OptimalControlBackend <: AbstractModelBackend end
struct JuMPBackend <: AbstractModelBackend end

function cart_pendulum(; model=:optimalcontrol)
     if model == :optimalcontrol
         cart_pendulum(OptimalControlBackend())
     elseif model == :jump
         cart_pendulum(JuMPBackend())
     else
          error("unknown model: ", model)
     end
end

# function to be extended
function cart_pendulum(model_backend::AbstractModelBackend, args...; kwargs...)
    if typeof(model_backend) == OptimalControlBackend
        throw(ExtensionError(:OptimalControl)) # this provides an error which tells to make julia> using OptimalControl
    elseif typeof(model_backend) == JuMPBackend
        throw(ExtensionError(:JuMP))
    end
end
```

In the extension for OptimalControl models we would have:

```julia
function cart_pendulum(model_backend::OptimalControlBackend, args...; kwargs...)
...
end
```

**Comment by ocots** [comment]
We can replace:

```julia
function cart_pendulum(; model=:optimalcontrol)
     if model == :optimalcontrol
         cart_pendulum(OptimalControlBackend())
     elseif model == :jump
         cart_pendulum(JuMPBackend())
     else
          error("unknown model: ", model)
     end
end
```

by

```julia
backends = Dict(:optimalcontrol => OptimalControlBackend, :jump => JuMPBackend)

function cart_pendulum(; model=:optimalcontrol)
    model ∈ keys(backends) ? cart_pendulum(backends[model]) : error("Unknown model: ", model)
end
```

**Comment by frapac** [comment]
Well, to be honest, I think this new version is way too complicated :) 
I think it's a bit overkill for a package that just aims at implementing a collections of optimal control instances. 

I am still convinced that we should stick to multiple dispatch. `JuMPBackend` and `OptimalControlBackend` should be defined in the their respective extensions. That way, the users can add new backends if they want too.

**Comment by ocots** [comment]
It was just for fun 😆

Extensions is the most important for me. 

We can do multiple dispatch or let like it is, both are fine for me. Between multiple dispatch or qualify the functions I have no preference.

**Comment by 0Yassine0** [comment]
Honestly, I'm having a hard time understanding how does the extension work. For this example :
> In [CTDirect.jl](https://github.com/control-toolbox/CTDirect.jl) you have an example of such a case. See [here](https://github.com/control-toolbox/CTDirect.jl/blob/5a2105a9026e7b01fce4c34267fdcc4e706e4342/src/solve.jl#L130-L143) to see how is defined the `solve_docp` function which returns the error and [here](https://github.com/control-toolbox/CTDirect.jl/blob/5a2105a9026e7b01fce4c34267fdcc4e706e4342/ext/CTSolveExtIpopt.jl#L15-L16) the extension which makes the job.

I tried to do the same with the `cart_pendulum` problem:
* Project.toml
```julia
[weakdeps]
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
OptimalControl = "5f98b655-cc9a-415a-b60e-744165666948"

[extensions]
JuMPModels = ["JuMP"]
OptimalControlModels = ["OptimalControl"]
```
* OptimalControlProblems
```julia
module OptimalControlProblems

abstract type AbstractModelBackend end
struct OptimalControlBackend <: AbstractModelBackend end
struct JuMPBackend <: AbstractModelBackend end

backends = Dict(:optimalcontrol => OptimalControlBackend, :jump => JuMPBackend)
weakdeps = Dict(OptimalControlBackend => :OptimalControl, JuMPBackend => :JuMP)

function cart_pendulum(; model=:optimalcontrol)
    if model == :optimalcontrol
        cart_pendulum(OptimalControlBackend())
    elseif model == :jump
        cart_pendulum(JuMPBackend())
    else
         error("unknown model: ", model)
    end
end

function cart_pendulum(model_backend::T, args...; kwargs...) where {T <: AbstractModelBackend}
end

end
```
* OptimalControlModels
```julia
module OptimalControlModels

using OptimalControlProblems

function OptimalControlProblems.cart_pendulum(model_backend::OptimalControlBackend;nh::Int=100)
    println("OK")
end

end
```
and to test it I run :
```julia
import Pkg
Pkg.activate(".")
using OptimalControlProblems
nlp = OptimalControlProblems.cart_pendulum(; model=:optimalcontrol)
```

And what I didn't understand is how the module of OptimalControlProblems calls `cart_pendulum` function of OptimalControlModels without any include or call between them ?

**Comment by ocots** [comment]
@0Yassine0 Point demain 9h.
