### ISSUE TITLE
[Dev] Add COTS models

### ISSUE THREAD

**Issue by 0Yassine0** [control-toolbox/OptimalControlProblems.jl#4]
From [COTS.jl](https://github.com/0Yassine0/COTS.jl/tree/main/Problems) package,  we will add the problems that works perfectly with `JuMP` and `OptimalControl` : 
The Hanging Chain, The Hang Glider, The Robot Arm, The Goddard Rocket, The Particle Steering, The Cart Pendulum, The Moonlander, The Dielectrophoretic Particle, The Ducted Fan, The Double Oscillator and The Electrical Vehicle.

**Comment by ocots** [comment]
@0Yassine0 When you have finished to add the problems, you can make a PR.

**Comment by frapac** [comment]
I would suggest we add the full list, including the problems where OC is not converging. 

As a reference, here is the list of all the problems we have so far:

- [ ] cart_pendulum
- [ ] chain
- [ ] ducted_fan
- [ ] electrical_vehicle
- [ ] glider
- [ ] moonlander
- [ ] oscillator
- [ ] particle
- [ ] quadrotor
- [ ] robot
- [ ] rocket
- [ ] space_Shuttle
- [ ] steering
- [ ] truck_trailer
- [ ] vanderpol

**Comment by 0Yassine0** [comment]
Yess I only used the models where we have the same results (nvar, ncon, objective value..) for the same nh.
I'll add the full list to the package if you're okay with that.
For the tests I checked that the solver gives an optimal solution, should I add a list to exclude the other models or I need to change the test?

**Comment by frapac** [comment]
Let's add the full list. 

For the tests, we should check that: 
- the return status is `MOI.LOCALLY_SOLVED` for JuMP, the equivalent for OC/NLPModels. 
- add `@test_broken` if Ipopt is not converging on a particular instance. That way, we can track which problems are failing.

**Comment by ocots** [comment]
@PierreMartinon do we have an equivalent of ?

**Comment by 0Yassine0** [comment]
> @PierreMartinon do we have an equivalent of `MOI.LOCALLY_SOLVED`?

Solving with OC has this field in its return value:  `sol.message`, so we can consider "Solve_Succeeded" as an equivalent of `MOI.LOCALLY_SOLVED`?

**Comment by ocots** [comment]
@0Yassine0 not sure. There is also `sol.success` but I am not sure this field is used.
