### ISSUE TITLE
[Dev] New package

### ISSUE THREAD

**Issue by ocots** [control-toolbox/OptimalControlProblems.jl#45]
@frapac @jbcaillau @PierreMartinon 

What do you think we need to do before trying to register `OptimalControlProblems.jl` into the General Julia registry?

**Comment by jbcaillau** [comment]
@ocots go!

NB. @0Yassine0 would be nice to use the new syntax `ocp = @def ...` (instead of `@def ocp ...`)

**Comment by ocots** [comment]
@JuliaRegistrator register()
